find . -iname SearchableSnapshotIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname TasksIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname SearchWeightedRoutingIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname IndexRecoveryIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname SegmentReplicationStatsIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname ShardIndexingPressureIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname DerivativeIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname FiltersIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname RemoveCorruptedShardDataCommandIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname RetentionLeaseIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname AdjacencyMatrixIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname ClusterDisruptionIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname IndexingPressureIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname PrimaryAllocationIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname RemoteIndexSnapshotStatusApiIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname SegmentReplicationRelocationIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname SegmentReplicationSnapshotIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname ShardIndexingPressureSettingsIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname CircuitBreakerServiceIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname CorruptedFileIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname DiskThresholdDeciderIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname GetTermVectorsIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname IndexStatsIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname MedianAbsoluteDeviationIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname RecoveryFromGatewayIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname RelocationIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname RemoteStoreForceMergeIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname SearchPreferenceIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname SegmentReplicationAllocationIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname SegmentReplicationClusterSettingIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname SegmentReplicationIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname SegmentReplicationPressureIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname SnapshotStatusApisIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname TruncatedRecoveryIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname AliasedIndexDocumentActionsIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname AllocationIdIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname BlobStoreIncrementalityIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname BulkRejectionIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname CloneSnapshotIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname ClusterManagerDisruptionIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname ClusterShardLimitIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname ClusterStatsIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname ConcurrentSearchTasksIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname ConcurrentSeqNoVersioningIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname DedicatedClusterSnapshotRestoreIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname DocumentActionsIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname EquivalenceIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname GetActionIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname MultiClusterRepoAccessIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname NoClusterManagerNodeIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname OpenCloseIndexIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname PrimaryTermValidationIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname ReplicaToPrimaryPromotionIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname RepositoriesIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname SearchTimeoutIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname SegmentReplicationUsingRemoteStoreIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname SingleNodeDiscoveryIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname TransportSearchFailuresIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
